# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true
plugins:
  - jekyll-gist



# edit here to achieve your personal greatness
url: http://arunasri.github.io
baseurl: /
location:
  address1: 10703 Campbell Commons Way
  address2: Charlotte, NC, 28277
title: Aruna Bolisetti
author: Aruna Sri Bolisetti
description: Personal blog and resume
avatar: aruna.jpg
email: ruby.aruna28@gmail.com
github: arunasri
twitter: barunasri
mobile_number: 479-856-2220
hobbies: Cooking, Gardening and Photography
google_analytics: UA-69391421-1
