# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://arunasri.github.io/
baseurl: /
location:
  address1: 20336 Briar Cliff Ter
  address2: Sterling, VA, 20165
title: Aruna Bolisetti
author: Aruna Sri Bolisetti
description: Personal blog and resume
avatar: aruna.jpg
email: rubu.aruna28@gmail.com
github: arunasri
twitter: barunasri
linkedin: username
disqus: username
mobile_number: 479-856-2220
hobbies: Cooking, Movies
google_analytics: UA-69391421-1
